[project]
name = "i"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "django>=5.1.6",
    "selenium>=4.28.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.6",
]
